### ISSUE TITLE
分词与不分词那个效果好？

### ISSUE THREAD

**Issue by DenceChen** [pengshuang/AI-Comp#1]
你好！请问你测试了吗？分词与不分词那个效果？我计算资源有限不能实现谢谢

**Comment by DenceChen** [comment]
@pengshuang 还有一个问题，请问：我跑下来感觉gru的那个模型更好点，适当调大gru的节点数据是不是效果会更好

**Comment by pengshuang** [comment]
不分词的RCNN+Attention效果最好

**Comment by DenceChen** [comment]
@pengshuang Bidirectional(GRU(1, return_sequences=True)) 我看你在RCNN实现的时候gru只是用了一个节点，你0.701就是基于这个网络算出来的？

**Comment by pengshuang** [comment]
代码update啦，128

**Comment by DenceChen** [comment]
@pengshuang encode2 = Bidirectional(CuDNNGRU(129, return_sequences=True))  encode2 你写的129

**Comment by pengshuang** [comment]
fix
